### ISSUE TITLE
Aero CTF 2020 - Drawings on the Wall

### ISSUE THREAD

**Issue by eljeffeg** [AeroCTF/aero-ctf-2021#1]
Tryiing to get in touch with the creator of the Aero CTF 2020 challenge "Drawings the wall".  I'm trying to create a similar challenge, but can't seem to get the memory dump to include the paint images (disabled pagefile).  Just wondering how it was created.  If you want a private chat, IM me on Twitter.

**Comment by eljeffeg** [comment]
Just figured I'd follow up and tag the devs @revervand , @keltecc , @MalumK ,  @zmir1 , @serega6531

**Comment by keltecc** [comment]
@eljeffeg hello, sorry for long delay. Some days ago we tried to find AeroCTF 2020 challenges in order to publish them. We've found almost all challenges, except two forensics, "Drawings on the walls" is among them. I'm sorry, but it seems the challenge is missing :(

Anyway you could try to connect the challenge author and ask him. You may find his contact in Aero CTF 2020 repository:
https://github.com/AeroCTF/aero-ctf-2020

Thanks
